apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: mongo-persistent
      labels:
        app: mongo
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: mongo-persistent-sa
      namespace: mongo-persistent
      labels:
        component: mongo-persistent
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: mongo
      namespace: mongo-persistent
      labels:
        app: mongo
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: gp2-csi
      resources:
        requests:
          storage: 1Gi
  - kind: SecurityContextConstraints
    apiVersion: security.openshift.io/v1
    metadata:
      name: mongo-persistent-scc
    allowPrivilegeEscalation: true
    allowPrivilegedContainer: true
    runAsUser:
      type: RunAsAny
    seLinuxContext:
      type: RunAsAny
    fsGroup:
      type: RunAsAny
    supplementalGroups:
      type: RunAsAny
    volumes:
    - '*'
    users:
    - system:admin
    - system:serviceaccount:mongo-persistent:mongo-persistent-sa
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
      name: mongo
      namespace: mongo-persistent
      labels:
        app: mongo
        service: mongo
    spec:
      ports:
      - protocol: TCP
        name: mongo
        port: 27017
      selector:
        app: mongo
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: mongo
      namespace: mongo-persistent
      labels:
        e2e-app: "true"
    spec:
      selector:
        matchLabels:
          app: mongo
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            e2e-app: "true"
            app: mongo
        spec:
          serviceAccountName: mongo-persistent-sa
          containers:
          - image: mongo:latest
            name: mongo
            securityContext:
              privileged: true
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: changeme
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: changeme
              - name: MONGO_INITDB_DATABASE
                value: todolist
            ports:
            - containerPort: 27017
              name: mongo
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          volumes:
          - name: mongo-data
            persistentVolumeClaim:
              claimName: mongo
  - apiVersion: v1
    kind: Service
    metadata:
      name: todolist
      namespace: mongo-persistent
      labels:
        app: todolist
        service: todolist
    spec:
      ports:
        - name: web
          port: 8000
          targetPort: 8000
      selector:
        app: todolist
        service: todolist
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: todolist
      namespace: mongo-persistent
      labels:
        app: todolist
        service: todolist
    spec:
      replicas: 1
      selector:
        app: todolist
        service: todolist
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: todolist
            service: todolist
        spec:
          containers:
          - name: todolist
            image:  quay.io/rhn_engineering_whayutin/todolist-mongo-go:2
            ports:
              - containerPort: 8000
                protocol: TCP
          initContainers:
          - name: init-myservice
            image: registry.access.redhat.com/ubi8/ubi:latest
            command: ['sh', '-c', 'sleep 10; until getent hosts mongo; do echo waiting for mongo; sleep 5; done;']
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: todolist-route
      namespace: mongo-persistent
    spec:
      path: "/"
      to:
        kind: Service
        name: todolist
