apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: todolist-mongo-go
      namespace: mongo-persistent
      labels:
        app.kubernetes.io/name: todolist-mongo-go
    spec:
      triggers:
      - type: GitHub
        github:
          secret: 4Xwu0tyAab90aaoasd88qweAasdaqvjknfrl3qwpo
      - type: Generic
        generic:
          secret: 4Xwu0tyAab90aaoasd88qweAasdaqvjknfrl3qwpo
      - type: ConfigChange
      - type: ImageChange
        imageChange: {}
      source:
        type: Git
        git:
          uri: https://github.com/weshayutin/todolist-mongo-go.git
          ref: master
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      output:
        to:
          kind: ImageStreamTag
          name: "todolist-mongo-go:latest"
      resources: {}
