apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        template.alpha.openshift.io/wait-for-ready: 'true'
      name: mongo
      namespace: mongo-persistent
      labels:
        e2e-app: "true"
    spec:
      selector:
        matchLabels:
          app: mongo
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            e2e-app: "true"
            app: mongo
        spec:
          serviceAccountName: mongo-persistent-sa
          containers:
          - image: mongo:latest
            name: mongo
            securityContext:
              privileged: true
            env:
              - name: MONGO_INITDB_ROOT_USERNAME
                value: changeme
              - name: MONGO_INITDB_ROOT_PASSWORD
                value: changeme
              - name: MONGO_INITDB_DATABASE
                value: todolist
            ports:
            - containerPort: 27017
              name: mongo
            resources:
              limits:
                memory: 512Mi
            volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          volumes:
          - name: mongo-data
            persistentVolumeClaim:
              claimName: mongo
