apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
      name: mongo
      namespace: mongo-persistent
      labels:
        app: mongo
        service: mongo
    spec:
      ports:
      - protocol: TCP
        name: mongo
        port: 27017
      selector:
        app: mongo