apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: mongo-persistent-sa
      namespace: mongo-persistent
      labels:
        component: mongo-persistent
