apiVersion: v1
kind: Service
metadata:
  name: todolist
  namespace: mongo-persistent
  labels:
    app: todolist
    service: todolist
spec:
  ports:
    - name: web
      port: 8000
      targetPort: 8000
  selector:
    app: todolist
    service: todolist
